version: '3.8'

services:
  cyberscope-web:
    build: .
    container_name: cyberscope-web
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s